# This file was generated by GoReleaser. DO NOT EDIT.
cask "mota" do
  name "mota"
  desc "A Shelly device firmware updater based on zeroconf (or bonjour) discovery for local networks using their built-in Over-The-Air update interface. It is suited for network setups where IoT devices do not have internet connectivity."
  homepage "https://github.com/ruimarinho/mota"
  version "3.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mota"

  on_macos do
    url "https://github.com/ruimarinho/mota/releases/download/v#{version}/mota_#{version}_macOS_all.tar.gz"
    sha256 "cd75a204df0992e545fb5943dbecdc69836b3e12c50bf17d2e41781672b2a5ce"
  end

  on_linux do
    on_intel do
      url "https://github.com/ruimarinho/mota/releases/download/v#{version}/mota_#{version}_Linux_x86_64.tar.gz"
      sha256 "9bed2e4878ff7b809322e6217098013762c49e09168a5069f024537516de9a68"
    end
  end

  # No zap stanza required
end
